blog:
  url: https://spring.io/blog/category/engineering.atom
  pollPeriodSec: 30

twitter:
  consumer:
    key: Obq8enorM0vUMaJVSI1T3Ko7j
    secret: p4jNizeMuX1i6XpiwvJ075qckyDIRx9r2Md9bLJwa7gmlpNrYY
  search:
    fetch-max: 10
    exclusions: tips

logging:
  level:
    root: INFO
spring:
  h2:
    console:
      enabled: true
  integration:
    jdbc:
      initialize-schema: never